select  mec.*, ww.*
from 
( 
  select 
  time_utc  
  ,max(case when station_call = 'KHBR' then wind_speed_kt end) as KHBR_kt
/*   ,max(case when station_call = 'KHBR' then wind_direction end) as KHBR_dir */
/*   ,max(case when station_call = 'KHBR' then temperature end) as KHBR_temp */
  ,max(case when station_call = 'KWLD' then wind_speed_kt end) as KWLD_kt
/*   ,max(case when station_call = 'KWLD' then wind_direction end) as KWLD_dir */
/*   ,max(case when station_call = 'KWLD' then temperature end) as KWLD_temp */
  ,max(case when station_call = 'KSWO' then wind_speed_kt end) as KSWO_kt
/*   ,max(case when station_call = 'KSWO' then wind_direction end) as KSWO_dir */
/*   ,max(case when station_call = 'KSWO' then temperature end) as KSWO_temp */
  ,max(case when station_call = 'KDDC' then wind_speed_kt end) as KDDC_kt
/*   ,max(case when station_call = 'KDDC' then wind_direction end) as KDDC_dir */
/*   ,max(case when station_call = 'KDDC' then temperature end) as KDDC_temp */
  ,max(case when station_call = 'KGCK' then wind_speed_kt end) as KGCK_kt
/*   ,max(case when station_call = 'KGCK' then wind_direction end) as KGCK_dir */
/*   ,max(case when station_call = 'KGCK' then temperature end) as KGCK_temp */
  ,max(case when station_call = 'KLBF' then wind_speed_kt end) as KLBF_kt
/*   ,max(case when station_call = 'KLBF' then wind_direction end) as KLBF_dir */
/*   ,max(case when station_call = 'KLBF' then temperature end) as KLBF_temp */
  ,max(case when station_call = 'KBGD' then wind_speed_kt end) as KBGD_kt
/*   ,max(case when station_call = 'KBGD' then wind_direction end) as KBGD_dir */
/*   ,max(case when station_call = 'KBGD' then temperature end) as KBGD_temp */
  ,max(case when station_call = 'KDHT' then wind_speed_kt end) as KDHT_kt
/*   ,max(case when station_call = 'KDHT' then wind_direction end) as KDHT_dir */
/*   ,max(case when station_call = 'KDHT' then temperature end) as KDHT_temp */
  ,max(case when station_call = 'KFDR' then wind_speed_kt end) as KFDR_kt
/*   ,max(case when station_call = 'KFDR' then wind_direction end) as KFDR_dir */
/*   ,max(case when station_call = 'KFDR' then temperature end) as KFDR_temp */
  ,max(case when station_call = 'KRWF' then wind_speed_kt end) as KRWF_kt
/*   ,max(case when station_call = 'KRWF' then wind_direction end) as KRWF_dir */
/*   ,max(case when station_call = 'KRWF' then temperature end) as KRWF_temp */
  ,max(case when station_call = 'KFOE' then wind_speed_kt end) as KFOE_kt
/*   ,max(case when station_call = 'KFOE' then wind_direction end) as KFOE_dir */
   ,max(case when station_call = 'KFOE' then temperature end) as KFOE_temp  /* Topeka KS */
  ,max(case when station_call = 'KBFF' then wind_speed_kt end) as KBFF_kt
/*   ,max(case when station_call = 'KBFF' then wind_direction end) as KBFF_dir */
/*   ,max(case when station_call = 'KBFF' then temperature end) as KBFF_temp */
  ,max(case when station_call = 'KSNY' then wind_speed_kt end) as KSNY_kt
/*   ,max(case when station_call = 'KSNY' then wind_direction end) as KSNY_dir */
/*   ,max(case when station_call = 'KSNY' then temperature end) as KSNY_temp */
  ,max(case when station_call = 'KITR' then wind_speed_kt end) as KITR_kt
/*   ,max(case when station_call = 'KITR' then wind_direction end) as KITR_dir */
/*   ,max(case when station_call = 'KITR' then temperature end) as KITR_temp */
  ,max(case when station_call = 'KABR' then wind_speed_kt end) as KABR_kt
/*   ,max(case when station_call = 'KABR' then wind_direction end) as KABR_dir */
/*   ,max(case when station_call = 'KABR' then temperature end) as KABR_temp */
  ,max(case when station_call = 'KGLD' then wind_speed_kt end) as KGLD_kt
/*   ,max(case when station_call = 'KGLD' then wind_direction end) as KGLD_dir */
/*   ,max(case when station_call = 'KGLD' then temperature end) as KGLD_temp */
  ,max(case when station_call = 'KLIT' then wind_speed_kt end) as KLIT_kt
/*   ,max(case when station_call = 'KLIT' then wind_direction end) as KLIT_dir */
/*   ,max(case when station_call = 'KLIT' then temperature end) as KLIT_temp */
  ,max(case when station_call = 'KAFW' then wind_speed_kt end) as KAFW_kt
/*   ,max(case when station_call = 'KAFW' then wind_direction end) as KAFW_dir */
/*   ,max(case when station_call = 'KAFW' then temperature end) as KAFW_temp */
  ,max(case when station_call = 'KCRS' then wind_speed_kt end) as KCRS_kt
/*   ,max(case when station_call = 'KCRS' then wind_direction end) as KCRS_dir */
/*   ,max(case when station_call = 'KCRS' then temperature end) as KCRS_temp */
  ,max(case when station_call = 'KSTJ' then wind_speed_kt end) as KSTJ_kt
/*   ,max(case when station_call = 'KSTJ' then wind_direction end) as KSTJ_dir */
/*   ,max(case when station_call = 'KSTJ' then temperature end) as KSTJ_temp */
  ,max(case when station_call = 'KTAD' then wind_speed_kt end) as KTAD_kt
/*   ,max(case when station_call = 'KTAD' then wind_direction end) as KTAD_dir */
/*   ,max(case when station_call = 'KTAD' then temperature end) as KTAD_temp */
  ,max(case when station_call = 'KLAR' then wind_speed_kt end) as KLAR_kt
/*   ,max(case when station_call = 'KLAR' then wind_direction end) as KLAR_dir */
/*   ,max(case when station_call = 'KLAR' then temperature end) as KLAR_temp */
  ,max(case when station_call = 'KSTC' then wind_speed_kt end) as KSTC_kt
/*   ,max(case when station_call = 'KSTC' then wind_direction end) as KSTC_dir */
/*   ,max(case when station_call = 'KSTC' then temperature end) as KSTC_temp */
  ,max(case when station_call = 'KHSI' then wind_speed_kt end) as KHSI_kt
/*   ,max(case when station_call = 'KHSI' then wind_direction end) as KHSI_dir */
/*   ,max(case when station_call = 'KHSI' then temperature end) as KHSI_temp */
  ,max(case when station_call = 'KPPF' then wind_speed_kt end) as KPPF_kt
/*   ,max(case when station_call = 'KPPF' then wind_direction end) as KPPF_dir */
/*   ,max(case when station_call = 'KPPF' then temperature end) as KPPF_temp */
  ,max(case when station_call = 'KRVS' then wind_speed_kt end) as KRVS_kt
/*   ,max(case when station_call = 'KRVS' then wind_direction end) as KRVS_dir */
/*   ,max(case when station_call = 'KRVS' then temperature end) as KRVS_temp */
  ,max(case when station_call = 'KMHK' then wind_speed_kt end) as KMHK_kt
/*   ,max(case when station_call = 'KMHK' then wind_direction end) as KMHK_dir */
/*   ,max(case when station_call = 'KMHK' then temperature end) as KMHK_temp */
  ,max(case when station_call = 'KDEQ' then wind_speed_kt end) as KDEQ_kt
/*   ,max(case when station_call = 'KDEQ' then wind_direction end) as KDEQ_dir */
/*   ,max(case when station_call = 'KDEQ' then temperature end) as KDEQ_temp */
  ,max(case when station_call = 'KCNM' then wind_speed_kt end) as KCNM_kt
/*   ,max(case when station_call = 'KCNM' then wind_direction end) as KCNM_dir */
/*   ,max(case when station_call = 'KCNM' then temperature end) as KCNM_temp */
  ,max(case when station_call = 'KRTN' then wind_speed_kt end) as KRTN_kt
/*   ,max(case when station_call = 'KRTN' then wind_direction end) as KRTN_dir */
/*   ,max(case when station_call = 'KRTN' then temperature end) as KRTN_temp */
  ,max(case when station_call = 'KGAG' then wind_speed_kt end) as KGAG_kt
/*   ,max(case when station_call = 'KGAG' then wind_direction end) as KGAG_dir */
/*   ,max(case when station_call = 'KGAG' then temperature end) as KGAG_temp */
  ,max(case when station_call = 'KISN' then wind_speed_kt end) as KISN_kt
/*   ,max(case when station_call = 'KISN' then wind_direction end) as KISN_dir */
/*   ,max(case when station_call = 'KISN' then temperature end) as KISN_temp */
  ,max(case when station_call = 'KFAR' then wind_speed_kt end) as KFAR_kt
/*   ,max(case when station_call = 'KFAR' then wind_direction end) as KFAR_dir */
/*   ,max(case when station_call = 'KFAR' then temperature end) as KFAR_temp */
  ,max(case when station_call = 'KDGW' then wind_speed_kt end) as KDGW_kt
/*   ,max(case when station_call = 'KDGW' then wind_direction end) as KDGW_dir */
/*   ,max(case when station_call = 'KDGW' then temperature end) as KDGW_temp */
  ,max(case when station_call = 'KAAO' then wind_speed_kt end) as KAAO_kt
/*   ,max(case when station_call = 'KAAO' then wind_direction end) as KAAO_dir */
/*   ,max(case when station_call = 'KAAO' then temperature end) as KAAO_temp */
  ,max(case when station_call = 'K8D3' then wind_speed_kt end) as K8D3_kt
/*   ,max(case when station_call = 'K8D3' then wind_direction end) as K8D3_dir */
/*   ,max(case when station_call = 'K8D3' then temperature end) as K8D3_temp */
  ,max(case when station_call = 'K2WX' then wind_speed_kt end) as K2WX_kt
/*   ,max(case when station_call = 'K2WX' then wind_direction end) as K2WX_dir */
/*   ,max(case when station_call = 'K2WX' then temperature end) as K2WX_temp */
  ,max(case when station_call = 'KGCC' then wind_speed_kt end) as KGCC_kt
/*   ,max(case when station_call = 'KGCC' then wind_direction end) as KGCC_dir */
/*   ,max(case when station_call = 'KGCC' then temperature end) as KGCC_temp */
  ,max(case when station_call = 'KJMS' then wind_speed_kt end) as KJMS_kt
/*   ,max(case when station_call = 'KJMS' then wind_direction end) as KJMS_dir */
/*   ,max(case when station_call = 'KJMS' then temperature end) as KJMS_temp */
  ,max(case when station_call = 'KCUT' then wind_speed_kt end) as KCUT_kt
/*   ,max(case when station_call = 'KCUT' then wind_direction end) as KCUT_dir */
/*   ,max(case when station_call = 'KCUT' then temperature end) as KCUT_temp */
  ,max(case when station_call = 'KMLS' then wind_speed_kt end) as KMLS_kt
/*   ,max(case when station_call = 'KMLS' then wind_direction end) as KMLS_dir */
/*   ,max(case when station_call = 'KMLS' then temperature end) as KMLS_temp */
  ,max(case when station_call = 'KCAO' then wind_speed_kt end) as KCAO_kt
/*   ,max(case when station_call = 'KCAO' then wind_direction end) as KCAO_dir */
/*   ,max(case when station_call = 'KCAO' then temperature end) as KCAO_temp */
  ,max(case when station_call = 'KBRD' then wind_speed_kt end) as KBRD_kt
/*   ,max(case when station_call = 'KBRD' then wind_direction end) as KBRD_dir */
/*   ,max(case when station_call = 'KBRD' then temperature end) as KBRD_temp */
  ,max(case when station_call = 'KLIC' then wind_speed_kt end) as KLIC_kt
/*   ,max(case when station_call = 'KLIC' then wind_direction end) as KLIC_dir */
/*   ,max(case when station_call = 'KLIC' then temperature end) as KLIC_temp */
  ,max(case when station_call = 'KIXD' then wind_speed_kt end) as KIXD_kt
/*   ,max(case when station_call = 'KIXD' then wind_direction end) as KIXD_dir */
/*   ,max(case when station_call = 'KIXD' then temperature end) as KIXD_temp */
  ,max(case when station_call = 'KTRL' then wind_speed_kt end) as KTRL_kt
/*   ,max(case when station_call = 'KTRL' then wind_direction end) as KTRL_dir */
/*   ,max(case when station_call = 'KTRL' then temperature end) as KTRL_temp */
  ,max(case when station_call = 'KOMA' then wind_speed_kt end) as KOMA_kt
/*   ,max(case when station_call = 'KOMA' then wind_direction end) as KOMA_dir */
/*   ,max(case when station_call = 'KOMA' then temperature end) as KOMA_temp */
  ,max(case when station_call = 'KLWC' then wind_speed_kt end) as KLWC_kt
/*   ,max(case when station_call = 'KLWC' then wind_direction end) as KLWC_dir */
/*   ,max(case when station_call = 'KLWC' then temperature end) as KLWC_temp */
  ,max(case when station_call = 'KFNB' then wind_speed_kt end) as KFNB_kt
/*   ,max(case when station_call = 'KFNB' then wind_direction end) as KFNB_dir */
/*   ,max(case when station_call = 'KFNB' then temperature end) as KFNB_temp */
  ,max(case when station_call = 'KTCC' then wind_speed_kt end) as KTCC_kt
/*   ,max(case when station_call = 'KTCC' then wind_direction end) as KTCC_dir */
/*   ,max(case when station_call = 'KTCC' then temperature end) as KTCC_temp */
  ,max(case when station_call = 'KAPA' then wind_speed_kt end) as KAPA_kt
/*   ,max(case when station_call = 'KAPA' then wind_direction end) as KAPA_dir */
/*   ,max(case when station_call = 'KAPA' then temperature end) as KAPA_temp */
  ,max(case when station_call = 'KPKD' then wind_speed_kt end) as KPKD_kt
/*   ,max(case when station_call = 'KPKD' then wind_direction end) as KPKD_dir */
/*   ,max(case when station_call = 'KPKD' then temperature end) as KPKD_temp */
  ,max(case when station_call = 'KCQC' then wind_speed_kt end) as KCQC_kt
/*   ,max(case when station_call = 'KCQC' then wind_direction end) as KCQC_dir */
/*   ,max(case when station_call = 'KCQC' then temperature end) as KCQC_temp */
  ,max(case when station_call = 'KDEN' then wind_speed_kt end) as KDEN_kt
/*   ,max(case when station_call = 'KDEN' then wind_direction end) as KDEN_dir */
/*   ,max(case when station_call = 'KDEN' then temperature end) as KDEN_temp */
  ,max(case when station_call = 'KGRI' then wind_speed_kt end) as KGRI_kt
/*   ,max(case when station_call = 'KGRI' then wind_direction end) as KGRI_dir */
/*   ,max(case when station_call = 'KGRI' then temperature end) as KGRI_temp */
  ,max(case when station_call = 'KLAW' then wind_speed_kt end) as KLAW_kt
/*   ,max(case when station_call = 'KLAW' then wind_direction end) as KLAW_dir */
   ,max(case when station_call = 'KLAW' then temperature end) as KLAW_temp             /* Lawton/Fort Sill in SW OK */
  ,max(case when station_call = 'KOLF' then wind_speed_kt end) as KOLF_kt
/*   ,max(case when station_call = 'KOLF' then wind_direction end) as KOLF_dir */
/*   ,max(case when station_call = 'KOLF' then temperature end) as KOLF_temp */
  ,max(case when station_call = 'KLAA' then wind_speed_kt end) as KLAA_kt
/*   ,max(case when station_call = 'KLAA' then wind_direction end) as KLAA_dir */
/*   ,max(case when station_call = 'KLAA' then temperature end) as KLAA_temp */
  ,max(case when station_call = 'KHON' then wind_speed_kt end) as KHON_kt
/*   ,max(case when station_call = 'KHON' then wind_direction end) as KHON_dir */
/*   ,max(case when station_call = 'KHON' then temperature end) as KHON_temp */
  ,max(case when station_call = 'KDIK' then wind_speed_kt end) as KDIK_kt
/*   ,max(case when station_call = 'KDIK' then wind_direction end) as KDIK_dir */
/*   ,max(case when station_call = 'KDIK' then temperature end) as KDIK_temp */
  ,max(case when station_call = 'KALS' then wind_speed_kt end) as KALS_kt
/*   ,max(case when station_call = 'KALS' then wind_direction end) as KALS_dir */
/*   ,max(case when station_call = 'KALS' then temperature end) as KALS_temp */
  ,max(case when station_call = 'KCSM' then wind_speed_kt end) as KCSM_kt
/*   ,max(case when station_call = 'KCSM' then wind_direction end) as KCSM_dir */
/*   ,max(case when station_call = 'KCSM' then temperature end) as KCSM_temp */
  ,max(case when station_call = 'KBBW' then wind_speed_kt end) as KBBW_kt
/*   ,max(case when station_call = 'KBBW' then wind_direction end) as KBBW_dir */
/*   ,max(case when station_call = 'KBBW' then temperature end) as KBBW_temp */
  ,max(case when station_call = 'KLVS' then wind_speed_kt end) as KLVS_kt
/*   ,max(case when station_call = 'KLVS' then wind_direction end) as KLVS_dir */
/*   ,max(case when station_call = 'KLVS' then temperature end) as KLVS_temp */
  ,max(case when station_call = 'KGKY' then wind_speed_kt end) as KGKY_kt
/*   ,max(case when station_call = 'KGKY' then wind_direction end) as KGKY_dir */
/*   ,max(case when station_call = 'KGKY' then temperature end) as KGKY_temp */
  ,max(case when station_call = 'KP28' then wind_speed_kt end) as KP28_kt
/*   ,max(case when station_call = 'KP28' then wind_direction end) as KP28_dir */
/*   ,max(case when station_call = 'KP28' then temperature end) as KP28_temp */
  ,max(case when station_call = 'KMHE' then wind_speed_kt end) as KMHE_kt
/*   ,max(case when station_call = 'KMHE' then wind_direction end) as KMHE_dir */
/*   ,max(case when station_call = 'KMHE' then temperature end) as KMHE_temp */
  ,max(case when station_call = 'KAIA' then wind_speed_kt end) as KAIA_kt
/*   ,max(case when station_call = 'KAIA' then wind_direction end) as KAIA_dir */
/*   ,max(case when station_call = 'KAIA' then temperature end) as KAIA_temp */
  ,max(case when station_call = 'KTOP' then wind_speed_kt end) as KTOP_kt
/*   ,max(case when station_call = 'KTOP' then wind_direction end) as KTOP_dir */
/*   ,max(case when station_call = 'KTOP' then temperature end) as KTOP_temp */
  ,max(case when station_call = 'KROW' then wind_speed_kt end) as KROW_kt
/*   ,max(case when station_call = 'KROW' then wind_direction end) as KROW_dir */
/*   ,max(case when station_call = 'KROW' then temperature end) as KROW_temp */
  ,max(case when station_call = 'KDFW' then wind_speed_kt end) as KDFW_kt
/*   ,max(case when station_call = 'KDFW' then wind_direction end) as KDFW_dir */
/*   ,max(case when station_call = 'KDFW' then temperature end) as KDFW_temp */
  ,max(case when station_call = 'KHUT' then wind_speed_kt end) as KHUT_kt
/*   ,max(case when station_call = 'KHUT' then wind_direction end) as KHUT_dir */
/*   ,max(case when station_call = 'KHUT' then temperature end) as KHUT_temp */
  ,max(case when station_call = 'KPIR' then wind_speed_kt end) as KPIR_kt
/*   ,max(case when station_call = 'KPIR' then wind_direction end) as KPIR_dir */
/*   ,max(case when station_call = 'KPIR' then temperature end) as KPIR_temp */
  ,max(case when station_call = 'KFSM' then wind_speed_kt end) as KFSM_kt
/*   ,max(case when station_call = 'KFSM' then wind_direction end) as KFSM_dir */
/*   ,max(case when station_call = 'KFSM' then temperature end) as KFSM_temp */
  ,max(case when station_call = 'KOKC' then wind_speed_kt end) as KOKC_kt
/*   ,max(case when station_call = 'KOKC' then wind_direction end) as KOKC_dir */
/*   ,max(case when station_call = 'KOKC' then temperature end) as KOKC_temp */
  ,max(case when station_call = 'KVTN' then wind_speed_kt end) as KVTN_kt
/*   ,max(case when station_call = 'KVTN' then wind_direction end) as KVTN_dir */
/*   ,max(case when station_call = 'KVTN' then temperature end) as KVTN_temp */
  ,max(case when station_call = 'KOFK' then wind_speed_kt end) as KOFK_kt
/*   ,max(case when station_call = 'KOFK' then wind_direction end) as KOFK_dir */
/*   ,max(case when station_call = 'KOFK' then temperature end) as KOFK_temp */
  ,max(case when station_call = 'KJLN' then wind_speed_kt end) as KJLN_kt
/*   ,max(case when station_call = 'KJLN' then wind_direction end) as KJLN_dir */
/*   ,max(case when station_call = 'KJLN' then temperature end) as KJLN_temp */
  ,max(case when station_call = 'KPWA' then wind_speed_kt end) as KPWA_kt
/*   ,max(case when station_call = 'KPWA' then wind_direction end) as KPWA_dir */
/*   ,max(case when station_call = 'KPWA' then temperature end) as KPWA_temp */
  ,max(case when station_call = 'KGGG' then wind_speed_kt end) as KGGG_kt
/*   ,max(case when station_call = 'KGGG' then wind_direction end) as KGGG_dir */
/*   ,max(case when station_call = 'KGGG' then temperature end) as KGGG_temp */
  ,max(case when station_call = 'KMOT' then wind_speed_kt end) as KMOT_kt
/*   ,max(case when station_call = 'KMOT' then wind_direction end) as KMOT_dir */
/*   ,max(case when station_call = 'KMOT' then temperature end) as KMOT_temp */
  ,max(case when station_call = 'KFYV' then wind_speed_kt end) as KFYV_kt
/*   ,max(case when station_call = 'KFYV' then wind_direction end) as KFYV_dir */
/*   ,max(case when station_call = 'KFYV' then temperature end) as KFYV_temp */
  ,max(case when station_call = 'KMKO' then wind_speed_kt end) as KMKO_kt
/*   ,max(case when station_call = 'KMKO' then wind_direction end) as KMKO_dir */
/*   ,max(case when station_call = 'KMKO' then temperature end) as KMKO_temp */
  ,max(case when station_call = 'KTXK' then wind_speed_kt end) as KTXK_kt
/*   ,max(case when station_call = 'KTXK' then wind_direction end) as KTXK_dir */
/*   ,max(case when station_call = 'KTXK' then temperature end) as KTXK_temp */
  ,max(case when station_call = 'KBVO' then wind_speed_kt end) as KBVO_kt
/*   ,max(case when station_call = 'KBVO' then wind_direction end) as KBVO_dir */
/*   ,max(case when station_call = 'KBVO' then temperature end) as KBVO_temp */
  ,max(case when station_call = 'KABI' then wind_speed_kt end) as KABI_kt
/*   ,max(case when station_call = 'KABI' then wind_direction end) as KABI_dir */
/*   ,max(case when station_call = 'KABI' then temperature end) as KABI_temp */
  ,max(case when station_call = 'KBIS' then wind_speed_kt end) as KBIS_kt
/*   ,max(case when station_call = 'KBIS' then wind_direction end) as KBIS_dir */
/*   ,max(case when station_call = 'KBIS' then temperature end) as KBIS_temp */
  ,max(case when station_call = 'KBDE' then wind_speed_kt end) as KBDE_kt
/*   ,max(case when station_call = 'KBDE' then wind_direction end) as KBDE_dir */
/*   ,max(case when station_call = 'KBDE' then temperature end) as KBDE_temp */
  ,max(case when station_call = 'KRAP' then wind_speed_kt end) as KRAP_kt
/*   ,max(case when station_call = 'KRAP' then wind_direction end) as KRAP_dir */
/*   ,max(case when station_call = 'KRAP' then temperature end) as KRAP_temp */
  ,max(case when station_call = 'KPHP' then wind_speed_kt end) as KPHP_kt
/*   ,max(case when station_call = 'KPHP' then wind_direction end) as KPHP_dir */
/*   ,max(case when station_call = 'KPHP' then temperature end) as KPHP_temp */
  ,max(case when station_call = 'KAKO' then wind_speed_kt end) as KAKO_kt
/*   ,max(case when station_call = 'KAKO' then wind_direction end) as KAKO_dir */
/*   ,max(case when station_call = 'KAKO' then temperature end) as KAKO_temp */
  ,max(case when station_call = 'KICR' then wind_speed_kt end) as KICR_kt
/*   ,max(case when station_call = 'KICR' then wind_direction end) as KICR_dir */
/*   ,max(case when station_call = 'KICR' then temperature end) as KICR_temp */
  ,max(case when station_call = 'KAXN' then wind_speed_kt end) as KAXN_kt
/*   ,max(case when station_call = 'KAXN' then wind_direction end) as KAXN_dir */
/*   ,max(case when station_call = 'KAXN' then temperature end) as KAXN_temp */
  ,max(case when station_call = 'KGFK' then wind_speed_kt end) as KGFK_kt
/*   ,max(case when station_call = 'KGFK' then wind_direction end) as KGFK_dir */
/*   ,max(case when station_call = 'KGFK' then temperature end) as KGFK_temp */
  ,max(case when station_call = 'KHLC' then wind_speed_kt end) as KHLC_kt
/*   ,max(case when station_call = 'KHLC' then wind_direction end) as KHLC_dir */
/*   ,max(case when station_call = 'KHLC' then temperature end) as KHLC_temp */
  ,max(case when station_call = 'KGOK' then wind_speed_kt end) as KGOK_kt
/*   ,max(case when station_call = 'KGOK' then wind_direction end) as KGOK_dir */
/*   ,max(case when station_call = 'KGOK' then temperature end) as KGOK_temp */
  ,max(case when station_call = 'KCNK' then wind_speed_kt end) as KCNK_kt
/*   ,max(case when station_call = 'KCNK' then wind_direction end) as KCNK_dir */
/*   ,max(case when station_call = 'KCNK' then temperature end) as KCNK_temp */
  ,max(case when station_call = 'KPUB' then wind_speed_kt end) as KPUB_kt
/*   ,max(case when station_call = 'KPUB' then wind_direction end) as KPUB_dir */
/*   ,max(case when station_call = 'KPUB' then temperature end) as KPUB_temp */
  ,max(case when station_call = 'KMCI' then wind_speed_kt end) as KMCI_kt
/*   ,max(case when station_call = 'KMCI' then wind_direction end) as KMCI_dir */
/*   ,max(case when station_call = 'KMCI' then temperature end) as KMCI_temp */
  ,max(case when station_call = 'KSUX' then wind_speed_kt end) as KSUX_kt
/*   ,max(case when station_call = 'KSUX' then wind_direction end) as KSUX_dir */
/*   ,max(case when station_call = 'KSUX' then temperature end) as KSUX_temp */
  ,max(case when station_call = 'KMBG' then wind_speed_kt end) as KMBG_kt
/*   ,max(case when station_call = 'KMBG' then wind_direction end) as KMBG_dir */
/*   ,max(case when station_call = 'KMBG' then temperature end) as KMBG_temp */
  ,max(case when station_call = 'KCNU' then wind_speed_kt end) as KCNU_kt
/*   ,max(case when station_call = 'KCNU' then wind_direction end) as KCNU_dir */
/*   ,max(case when station_call = 'KCNU' then temperature end) as KCNU_temp */
  ,max(case when station_call = 'KSPS' then wind_speed_kt end) as KSPS_kt
/*   ,max(case when station_call = 'KSPS' then wind_direction end) as KSPS_dir */
/*   ,max(case when station_call = 'KSPS' then temperature end) as KSPS_temp */
  ,max(case when station_call = 'KRBD' then wind_speed_kt end) as KRBD_kt
/*   ,max(case when station_call = 'KRBD' then wind_direction end) as KRBD_dir */
/*   ,max(case when station_call = 'KRBD' then temperature end) as KRBD_temp */
  ,max(case when station_call = 'KOJC' then wind_speed_kt end) as KOJC_kt
/*   ,max(case when station_call = 'KOJC' then wind_direction end) as KOJC_dir */
/*   ,max(case when station_call = 'KOJC' then temperature end) as KOJC_temp */
  ,max(case when station_call = 'KSPW' then wind_speed_kt end) as KSPW_kt
/*   ,max(case when station_call = 'KSPW' then wind_direction end) as KSPW_dir */
/*   ,max(case when station_call = 'KSPW' then temperature end) as KSPW_temp */
  ,max(case when station_call = 'KLXT' then wind_speed_kt end) as KLXT_kt
/*   ,max(case when station_call = 'KLXT' then wind_direction end) as KLXT_dir */
/*   ,max(case when station_call = 'KLXT' then temperature end) as KLXT_temp */
  ,max(case when station_call = 'KSPD' then wind_speed_kt end) as KSPD_kt
/*   ,max(case when station_call = 'KSPD' then wind_direction end) as KSPD_dir */
/*   ,max(case when station_call = 'KSPD' then temperature end) as KSPD_temp */
  ,max(case when station_call = 'KN60' then wind_speed_kt end) as KN60_kt
/*   ,max(case when station_call = 'KN60' then wind_direction end) as KN60_dir */
/*   ,max(case when station_call = 'KN60' then temperature end) as KN60_temp */
  ,max(case when station_call = 'KXNA' then wind_speed_kt end) as KXNA_kt
/*   ,max(case when station_call = 'KXNA' then wind_direction end) as KXNA_dir */
/*   ,max(case when station_call = 'KXNA' then temperature end) as KXNA_temp */
  ,max(case when station_call = 'KMWL' then wind_speed_kt end) as KMWL_kt
/*   ,max(case when station_call = 'KMWL' then wind_direction end) as KMWL_dir */
/*   ,max(case when station_call = 'KMWL' then temperature end) as KMWL_temp */
  ,max(case when station_call = 'KPNC' then wind_speed_kt end) as KPNC_kt
/*   ,max(case when station_call = 'KPNC' then wind_direction end) as KPNC_dir */
/*   ,max(case when station_call = 'KPNC' then temperature end) as KPNC_temp */
  ,max(case when station_call = 'KIML' then wind_speed_kt end) as KIML_kt
/*   ,max(case when station_call = 'KIML' then wind_direction end) as KIML_dir */
/*   ,max(case when station_call = 'KIML' then temperature end) as KIML_temp */
  ,max(case when station_call = 'KDAL' then wind_speed_kt end) as KDAL_kt
/*   ,max(case when station_call = 'KDAL' then wind_direction end) as KDAL_dir */
/*   ,max(case when station_call = 'KDAL' then temperature end) as KDAL_temp */
  ,max(case when station_call = 'KTOR' then wind_speed_kt end) as KTOR_kt
/*   ,max(case when station_call = 'KTOR' then wind_direction end) as KTOR_dir */
/*   ,max(case when station_call = 'KTOR' then temperature end) as KTOR_temp */
  ,max(case when station_call = 'KCOS' then wind_speed_kt end) as KCOS_kt
/*   ,max(case when station_call = 'KCOS' then wind_direction end) as KCOS_dir */
/*   ,max(case when station_call = 'KCOS' then temperature end) as KCOS_temp */
  ,max(case when station_call = 'KTQE' then wind_speed_kt end) as KTQE_kt
/*   ,max(case when station_call = 'KTQE' then wind_direction end) as KTQE_dir */
/*   ,max(case when station_call = 'KTQE' then temperature end) as KTQE_temp */
  ,max(case when station_call = 'KMKC' then wind_speed_kt end) as KMKC_kt
/*   ,max(case when station_call = 'KMKC' then wind_direction end) as KMKC_dir */
/*   ,max(case when station_call = 'KMKC' then temperature end) as KMKC_temp */
  ,max(case when station_call = 'KFSD' then wind_speed_kt end) as KFSD_kt
/*   ,max(case when station_call = 'KFSD' then wind_direction end) as KFSD_dir */
/*   ,max(case when station_call = 'KFSD' then temperature end) as KFSD_temp */
  ,max(case when station_call = 'KIEN' then wind_speed_kt end) as KIEN_kt
/*   ,max(case when station_call = 'KIEN' then wind_direction end) as KIEN_dir */
/*   ,max(case when station_call = 'KIEN' then temperature end) as KIEN_temp */
  ,max(case when station_call = 'KGUY' then wind_speed_kt end) as KGUY_kt
/*  ,max(case when station_call = 'KGUY' then wind_direction end) as KGUY_dir  */
/*  ,max(case when station_call = 'KGUY' then temperature end) as KGUY_temp  */  /* guymon, OK */
  ,max(case when station_call = 'KLHX' then wind_speed_kt end) as KLHX_kt
/*   ,max(case when station_call = 'KLHX' then wind_direction end) as KLHX_dir */
/*   ,max(case when station_call = 'KLHX' then temperature end) as KLHX_temp */
  ,max(case when station_call = 'KCYS' then wind_speed_kt end) as KCYS_kt
/*   ,max(case when station_call = 'KCYS' then wind_direction end) as KCYS_dir */
/*   ,max(case when station_call = 'KCYS' then temperature end) as KCYS_temp */
  ,max(case when station_call = 'KATY' then wind_speed_kt end) as KATY_kt
/*   ,max(case when station_call = 'KATY' then wind_direction end) as KATY_dir */
/*   ,max(case when station_call = 'KATY' then temperature end) as KATY_temp */
  ,max(case when station_call = 'KEMP' then wind_speed_kt end) as KEMP_kt
/*   ,max(case when station_call = 'KEMP' then wind_direction end) as KEMP_dir */
/*   ,max(case when station_call = 'KEMP' then temperature end) as KEMP_temp */
  ,max(case when station_call = 'KEST' then wind_speed_kt end) as KEST_kt
/*   ,max(case when station_call = 'KEST' then wind_direction end) as KEST_dir */
/*   ,max(case when station_call = 'KEST' then temperature end) as KEST_temp */
  ,max(case when station_call = 'KTKI' then wind_speed_kt end) as KTKI_kt
/*   ,max(case when station_call = 'KTKI' then wind_direction end) as KTKI_dir */
/*   ,max(case when station_call = 'KTKI' then temperature end) as KTKI_temp */
  ,max(case when station_call = 'KDTO' then wind_speed_kt end) as KDTO_kt
/*   ,max(case when station_call = 'KDTO' then wind_direction end) as KDTO_dir */
/*   ,max(case when station_call = 'KDTO' then temperature end) as KDTO_temp */
  ,max(case when station_call = 'KAMA' then wind_speed_kt end) as KAMA_kt
/*   ,max(case when station_call = 'KAMA' then wind_direction end) as KAMA_dir */
/*   ,max(case when station_call = 'KAMA' then temperature end) as KAMA_temp */
  ,max(case when station_call = 'KMLC' then wind_speed_kt end) as KMLC_kt
/*   ,max(case when station_call = 'KMLC' then wind_direction end) as KMLC_dir */
/*   ,max(case when station_call = 'KMLC' then temperature end) as KMLC_temp */
  ,max(case when station_call = 'KLBB' then wind_speed_kt end) as KLBB_kt
/*   ,max(case when station_call = 'KLBB' then wind_direction end) as KLBB_dir */
/*   ,max(case when station_call = 'KLBB' then temperature end) as KLBB_temp */
  ,max(case when station_call = 'KICT' then wind_speed_kt end) as KICT_kt
/*   ,max(case when station_call = 'KICT' then wind_direction end) as KICT_dir */
/*   ,max(case when station_call = 'KICT' then temperature end) as KICT_temp */
  ,max(case when station_call = 'KMCK' then wind_speed_kt end) as KMCK_kt
/*   ,max(case when station_call = 'KMCK' then wind_direction end) as KMCK_dir */
/*   ,max(case when station_call = 'KMCK' then temperature end) as KMCK_temp */
  ,max(case when station_call = 'KODX' then wind_speed_kt end) as KODX_kt
/*   ,max(case when station_call = 'KODX' then wind_direction end) as KODX_dir */
/*   ,max(case when station_call = 'KODX' then temperature end) as KODX_temp */
  ,max(case when station_call = 'KCDS' then wind_speed_kt end) as KCDS_kt
/*   ,max(case when station_call = 'KCDS' then wind_direction end) as KCDS_dir */
/*   ,max(case when station_call = 'KCDS' then temperature end) as KCDS_temp */
  ,max(case when station_call = 'KRSL' then wind_speed_kt end) as KRSL_kt
/*   ,max(case when station_call = 'KRSL' then wind_direction end) as KRSL_dir */
/*   ,max(case when station_call = 'KRSL' then temperature end) as KRSL_temp */
  ,max(case when station_call = 'KBHK' then wind_speed_kt end) as KBHK_kt
/*   ,max(case when station_call = 'KBHK' then wind_direction end) as KBHK_dir */
/*   ,max(case when station_call = 'KBHK' then temperature end) as KBHK_temp */
  ,max(case when station_call = 'KTUL' then wind_speed_kt end) as KTUL_kt
/*   ,max(case when station_call = 'KTUL' then wind_direction end) as KTUL_dir */
/*   ,max(case when station_call = 'KTUL' then temperature end) as KTUL_temp */
  ,max(case when station_call = 'KTYR' then wind_speed_kt end) as KTYR_kt
/*   ,max(case when station_call = 'KTYR' then wind_direction end) as KTYR_dir */
/*   ,max(case when station_call = 'KTYR' then temperature end) as KTYR_temp */
  ,max(case when station_call = 'KLNK' then wind_speed_kt end) as KLNK_kt
/*   ,max(case when station_call = 'KLNK' then wind_direction end) as KLNK_dir */
/*   ,max(case when station_call = 'KLNK' then temperature end) as KLNK_temp */
  ,max(case when station_call = 'KD07' then wind_speed_kt end) as KD07_kt
/*   ,max(case when station_call = 'KD07' then wind_direction end) as KD07_dir */
/*   ,max(case when station_call = 'KD07' then temperature end) as KD07_temp */
  ,max(case when station_call = 'KCDR' then wind_speed_kt end) as KCDR_kt
/*   ,max(case when station_call = 'KCDR' then wind_direction end) as KCDR_dir */
/*   ,max(case when station_call = 'KCDR' then temperature end) as KCDR_temp */
  from weather_clean
  group by 1 
) ww
join 
( 
  select intervalbegin, 
  case /* when mec <= -9.4804 then
       when mec >= 160.8341 then 1 */ 
       when lmp <= 0 then 1  
  else 0 end as spp_price_event_flag, 
  least(lmp,100) as lmp
  from spprtbm_stg
  /* where settlement_location = 'SPPSOUTH_HUB' */
  where settlement_location = 'CSWS.AECC.DRIFTSAND'
) mec
on (ww.time_utc = mec.intervalbegin) 
--where extract(MINUTE from ww.time_utc) in (5,20,35,50)


